import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultProfile,validateProfile,calculatePayroll,annualTax,zeroYTD,createRun,verifyRun,voidRun,ytdFor} from '../public/payroll.js';
import {emptyJournal,validateJournal} from '../public/core.js';
function profile(){return {...defaultProfile(),startDate:'2025-01-01',confirmed:true,vacationAgreement:true};}
function input(){return {start:'2026-09-20',end:'2026-09-26',payDate:'2026-09-30',regular:100000,stat:0,other:0,vacationBase:100000,reviewed:true,note:''};}
function fixture(){const db=emptyJournal();db.staff.push({id:'s',name:'Example',code:'S',active:true,rates:[{effective:'2025-01-01',cents:2000}],payroll:profile()});return db;}
test('CRA published CPP2 example: 75200 YTD + 1600 pay crosses no further threshold',()=>{const y={...zeroYTD(),gross:7520000,pensionable:7520000,insurable:7520000,cpp:423045,cpp2:2400,ei:112307};const r=calculatePayroll({...input(),regular:160000,vacationBase:160000},profile(),y);assert.equal(r.cpp,0);assert.equal(r.cpp2,6656);assert.equal(r.ei,0);assert.equal(r.gross,166400);});
test('CRA T4127 bonus example reproduces federal bonus tax $323.54',()=>{const p={...profile(),vacationPercent:25};const y={...zeroYTD(),gross:3050000,pensionable:3050000,insurable:3050000,cpp:169875,ei:49715,bonus:150000,bonusEnhanced:1460,bonusCpp:8925,bonusEi:2445};const r=calculatePayroll({...input(),payDate:'2026-06-30',start:'2026-06-21',end:'2026-06-27',vacationBase:1000000},p,y);assert.equal(r.gross,350000);assert.equal(r.cpp,20425);assert.equal(r.bonusEnhanced,2452);assert.equal(r.bonusFederal,32354);});
test('CRA T4032 annual formula reference: above YMPE federal 9406.39 and BC 3916.50',()=>{const r=annualTax(79872,83200,3519.45,1123.07,profile(),false);assert.equal(r.federal,9406.39);assert.equal(r.bc,3916.5);});
test('July pay-date update changes BC only',()=>{const i={...input(),start:'2026-06-21',end:'2026-06-27'};const jan=calculatePayroll({...i,payDate:'2026-06-30'},profile(),zeroYTD()),jul=calculatePayroll({...i,payDate:'2026-07-01'},profile(),zeroYTD());assert.equal(jan.federal,jul.federal);assert.notEqual(jan.bc,jul.bc);assert.match(jul.table,/July/);});
test('EI exemption is employee-specific and removes employer EI too',()=>{const p={...profile(),ei:false,exemptionReason:'Confirmed non-insurable employment'};const r=calculatePayroll(input(),p,zeroYTD()),ordinary=calculatePayroll(input(),profile(),zeroYTD());assert.equal(r.ei,0);assert.equal(r.employerEi,0);assert.ok(r.cpp>0);assert.ok(r.tax>ordinary.tax);});
test('CPP and EI caps, CPP2 threshold crossing and exact money reconciliation',()=>{const y={...zeroYTD(),pensionable:7450000,cpp:422000,ei:112000};const r=calculatePayroll(input(),profile(),y);assert.equal(r.cpp,1045);assert.equal(r.cpp2,3760);assert.equal(r.ei,307);assert.equal(r.net+r.tax+r.cpp+r.cpp2+r.ei,r.gross);assert.equal(r.employerCpp,r.cpp+r.cpp2);});
test('zero TD1 claims do not become basic claims',()=>{const a=calculatePayroll(input(),profile(),zeroYTD()),b=calculatePayroll(input(),{...profile(),federalClaim:0,bcClaim:0},zeroYTD());assert.ok(b.tax>a.tax);});
test('2027, incomplete profiles, invalid periods and unsupported vacation-only payments block',()=>{assert.throws(()=>calculatePayroll({...input(),payDate:'2027-01-01'},profile(),zeroYTD()),/2026/);assert.throws(()=>calculatePayroll(input(),{...profile(),confirmed:false},zeroYTD()),/confirm/);assert.throws(()=>calculatePayroll({...input(),end:'2026-09-25'},profile(),zeroYTD()),/seven-day/);assert.throws(()=>calculatePayroll({...input(),regular:0},profile(),zeroYTD()),/positive/);assert.throws(()=>validateProfile({...profile(),ei:false}),/reason/);});
test('five-year vacation entitlement cannot stay at 4%',()=>{assert.throws(()=>calculatePayroll(input(),{...profile(),startDate:'2020-01-01'},zeroYTD()),/6%/);const r=calculatePayroll(input(),{...profile(),startDate:'2020-01-01',vacationPercent:6},zeroYTD());assert.equal(r.vacation,6000);});
test('commission example 525 at 50% gives 262.50 plus 4% vacation',()=>{const r=calculatePayroll({...input(),regular:26250,vacationBase:26250},profile(),zeroYTD());assert.equal(r.vacation,1050);assert.equal(r.gross,27300);});
test('one unverified estimate at a time; duplicate periods rejected',()=>{const db=fixture(),r=createRun(db,'s',input(),'r');db.payrollRuns=[r];assert.throws(()=>createRun(db,'s',input(),'r2'),/already/);assert.throws(()=>ytdFor(db,'s','2026-10-07'),/Verify/);});
test('verification preserves estimate, advances YTD using actual corrections and requires note',()=>{const db=fixture(),r=createRun(db,'s',input(),'r');db.payrollRuns=[r];const original=structuredClone(r.estimate),actual=Object.fromEntries(['cpp','cpp2','ei','tax','bonusEnhanced','bonusCpp','bonusEi'].map(k=>[k,r.estimate[k]]));assert.throws(()=>verifyRun(r,actual,''),/note/);actual.tax+=100;verifyRun(r,actual,'Compared with CRA example');assert.deepEqual(r.estimate,original);const y=ytdFor(db,'s','2026-10-07');assert.equal(y.tax,actual.tax);assert.equal(y.bonus,r.estimate.vacation);assert.equal(y.gross,r.estimate.gross);assert.equal(r.actual.net,r.estimate.net-100);assert.equal(validateJournal(structuredClone(db)).payrollRuns[0].status,'verified');});
test('later records must be voided first; voiding excludes them from YTD',()=>{const db=fixture(),r=createRun(db,'s',input(),'r');db.payrollRuns=[r];verifyRun(r,r.estimate,'Checked');const r2=createRun(db,'s',{...input(),start:'2026-09-27',end:'2026-10-03',payDate:'2026-10-07'},'r2');db.payrollRuns.push(r2);assert.throws(()=>voidRun(db,'r','Correction'),/later/);voidRun(db,'r2','Correcting earlier payroll');voidRun(db,'r','Correction');assert.deepEqual(ytdFor(db,'s','2026-10-14'),profile().opening);});
test('old journals still load and corrupted payroll is rejected',()=>{assert.ok(validateJournal(emptyJournal()));const db=fixture();db.payrollRuns=[createRun(db,'s',input(),'r')];assert.ok(validateJournal(structuredClone(db)));db.payrollRuns[0].estimate.tax+=1;assert.throws(()=>validateJournal(db),/saved inputs/);});
test('CRA corrections cannot exceed annual caps or contradict an exemption',()=>{const db=fixture(),r=createRun(db,'s',input(),'r');assert.throws(()=>verifyRun(r,{...r.estimate,ei:112308},'Correction'),/annual limits/);db.staff[0].payroll.ei=false;db.staff[0].payroll.exemptionReason='Confirmed exemption';const exempt=createRun(db,'s',input(),'r2');assert.throws(()=>verifyRun(exempt,{...exempt.estimate,ei:1},'Correction'),/exemption/);});
test('pending cards block pay and missing written vacation agreement blocks estimate',()=>{const db=fixture();db.timecards.push({staffId:'s',date:'2026-09-21',status:'pending'});assert.throws(()=>createRun(db,'s',input(),'r'),/pending/);assert.throws(()=>calculatePayroll(input(),{...profile(),vacationAgreement:false},zeroYTD()),/agreement/);});
test('five-digit earnings and all 52 weekly calculations remain within yearly caps',()=>{const db=fixture();let cpp=0,cpp2=0,ei=0;for(let n=0;n<52;n++){const date=new Date('2026-01-01T12:00:00Z');date.setUTCDate(date.getUTCDate()+n*7);const start=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+6);const end=date.toISOString().slice(0,10);const r=createRun(db,'s',{...input(),start,end,payDate:end,regular:200000,vacationBase:200000},'r'+n);(db.payrollRuns??=[]).push(r);verifyRun(r,r.estimate,'Synthetic test');cpp+=r.actual.cpp;cpp2+=r.actual.cpp2;ei+=r.actual.ei;}assert.equal(cpp,423045);assert.equal(cpp2,41600);assert.equal(ei,112307);assert.ok(validateJournal(db));});
