import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyJournal,ensureMonth,earned,dayTotals,totals,staffingByDay,cardIssue,validateJournal} from '../public/core.js';
import {defaultProfile,createRun,verifyRun,recordPayrollPayment,voidRun} from '../public/payroll.js';
import {rolesFor,allocateCents,payrollCostDays,payrollAlerts,periodLocked,holidayEvidence,holidayReviewed} from '../public/workflow-core.js';
import {journalFiles,newJournalFile,JournalStore} from '../public/storage.js';
function fixture(){const d=emptyJournal();ensureMonth(d,'2026-03');d.staff=[{id:'s',name:'Employee',code:'S',active:true,mainJob:'Bathing',rates:[{effective:'2026-01-01',cents:2000}],roles:[{id:'groom',name:'Grooming',rates:[{effective:'2026-01-01',kind:'commission',cents:5000},{effective:'2026-03-15',kind:'commission',cents:5500}]}],payroll:{...defaultProfile(),startDate:'2025-01-01',confirmed:true,vacationAgreement:true}}];return d;}
function card(id,date,minutes=480){return {id,staffId:'s',date,minutes,start:'09:00',end:'17:00',status:'approved',note:''};}
function run(db,start='2026-03-01',end='2026-03-07'){const regular=db.timecards.filter(c=>c.date>=start&&c.date<=end&&c.status==='approved').reduce((n,c)=>n+earned(db,c),0)||100000;return createRun(db,'s',{start,end,payDate:end,regular,stat:0,other:0,vacationBase:regular,reviewed:true,note:'',costDays:payrollCostDays(db,'s',start,end,earned)},'r');}
test('legacy hourly employees keep one job and old cards keep their rates',()=>{const db=fixture();delete db.staff[0].roles;assert.equal(rolesFor(db.staff[0]).length,1);assert.equal(earned(db,card('c','2026-03-02')),16000);});
test('commission cards use date-specific job rate and require sales',()=>{const db=fixture(),c={...card('c','2026-03-14'),roleId:'groom',sales:52500};assert.equal(earned(db,c),26250);c.date='2026-03-15';assert.equal(earned(db,c),28875);delete c.sales;assert.match(cardIssue(db,c),/sales/);});
test('invalid roles and commission percentages fail journal loading',()=>{const db=fixture();db.timecards=[{...card('c','2026-03-02'),roleId:'missing'}];assert.throws(()=>validateJournal(db));db.timecards=[];db.staff[0].roles[0].rates[0].cents=10001;assert.throws(()=>validateJournal(db));});
test('recovered commission sales retain missing hours without inventing a shift',()=>{const db=fixture();const c={...card('recovered','2026-03-02'),roleId:'groom',sales:52500,minutes:null,hoursMissing:true,start:'',end:'',status:'pending'};db.timecards=[c];assert.ok(validateJournal(db));assert.equal(earned(db,c),26250);assert.match(cardIssue(db,c),/Hours/);c.status='approved';assert.throws(()=>validateJournal(db));c.status='pending';c.roleId='default';assert.throws(()=>validateJournal(db));c.roleId='groom';c.minutes=120;delete c.hoursMissing;assert.equal(cardIssue(db,c),'');assert.ok(validateJournal(db));});
test('staffing includes vacation and employer contributions before payroll',()=>{const db=fixture();db.timecards=[card('c','2026-03-02')];db.months['2026-03'].days['2026-03-02'].sales=50000;const t=dayTotals(db,'2026-03','2026-03-02');assert.ok(t.staffing>16640);assert.equal(t.clear,50000-t.staffing);assert.equal(t.staffingEstimated,true);});
test('saved payroll replaces time-card estimates without double charging',()=>{const db=fixture();db.timecards=[card('c','2026-03-02'),card('d','2026-03-03')];const r=run(db);db.payrollRuns=[r];const costs=staffingByDay(db);assert.equal(Object.values(costs).reduce((a,c)=>a+c.cost,0),r.estimate.employerCost);assert.equal(periodLocked(db,'s','2026-03-02'),true);assert.match(cardIssue(db,card('new','2026-03-04')),/Payroll/);verifyRun(r,r.estimate,'Test review');const before=totals(db,'2026-03').clear;recordPayrollPayment(db,'r','pay');assert.equal(totals(db,'2026-03').clear,before);assert.throws(()=>recordPayrollPayment(db,'r','pay2'),/already/);assert.throws(()=>voidRun(db,'r','Correct'),/payment/);assert.ok(validateJournal(db));});
test('cross-month payroll is allocated to work dates and reconciles to exact cents',()=>{const db=fixture();ensureMonth(db,'2026-04');db.timecards=[card('c','2026-03-31',60),card('d','2026-04-01',120)];const r=run(db,'2026-03-29','2026-04-04');db.payrollRuns=[r];const c=staffingByDay(db);assert.equal(c['2026-03-31'].cost+c['2026-04-01'].cost,r.estimate.employerCost);assert.equal(totals(db,'2026-03').staffing,c['2026-03-31'].cost);assert.equal(totals(db,'2026-04').staffing,c['2026-04-01'].cost);assert.deepEqual(allocateCents(100,{'2026-03-31':1,'2026-04-01':2}),{'2026-03-31':33,'2026-04-01':67});});
test('staffing cost dates stay fixed if the working-day calendar changes',()=>{const db=fixture(),r=run(db);db.payrollRuns=[r];const before=staffingByDay(db);db.months['2026-03'].days['2026-03-02'].status='cancelled';assert.deepEqual(staffingByDay(db),before);});
test('missing setup and pending time cards never show an overstated clear figure',()=>{const db=fixture();db.timecards=[card('c','2026-03-02')];delete db.staff[0].payroll;assert.equal(totals(db,'2026-03').clear,null);db.timecards[0].status='pending';assert.equal(dayTotals(db,'2026-03','2026-03-02').staffing,null);});
test('costs on days without sales still reduce monthly money left',()=>{const db=fixture();db.timecards=[card('c','2026-03-02')];const t=totals(db,'2026-03');assert.equal(t.sales,0);assert.equal(t.clear,-t.staffing);});
test('overtime alerts combine jobs per day and use Sunday weeks',()=>{const db=fixture();db.timecards=[card('a','2026-03-02',300),{...card('b','2026-03-02',300),roleId:'groom',sales:50000},...['03','04','05','06'].map(d=>card(d,'2026-03-'+d))];const alerts=payrollAlerts(db,'s','2026-03-01','2026-03-07');assert.equal(alerts.overtime.length,2);assert.match(alerts.overtime[0],/10.00/);});
test('holiday alerts do not confuse recorded days with complete eligibility',()=>{const db=fixture();const a=payrollAlerts(db,'s','2026-09-27','2026-10-03');assert.equal(a.holidays[0].date,'2026-09-30');assert.equal(a.holidays[0].recordedDays,0);assert.equal(a.holidays[0].worked,false);});
test('a no-entitlement holiday review resolves a no-hours month and reopens after relevant changes',()=>{const db=fixture();ensureMonth(db,'2026-02');assert.equal(totals(db,'2026-02').clear,null);db.holidayReviews=[{staffId:'s',date:'2026-02-16',note:'Complete records checked; no entitlement',evidence:holidayEvidence(db,'s','2026-02-16')}];assert.equal(totals(db,'2026-02').clear,0);assert.ok(validateJournal(db));db.timecards.push(card('new','2026-02-12'));assert.equal(holidayReviewed(db,'s','2026-02-16'),false);assert.equal(totals(db,'2026-02').clear,null);db.holidayReviews[0].evidence=holidayEvidence(db,'s','2026-02-16');db.staff[0].payroll.startDate='2024-01-01';assert.equal(holidayReviewed(db,'s','2026-02-16'),false);});
test('holiday reviews reject unknown employees and duplicate dates on load',()=>{const db=fixture();db.holidayReviews=[{staffId:'missing',date:'2026-02-16',note:'Reason',evidence:''}];assert.throws(()=>validateJournal(db));db.holidayReviews[0].staffId='s';db.holidayReviews.push({...db.holidayReviews[0]});assert.throws(()=>validateJournal(db));});
test('new folder creation does not overwrite an existing journal',async()=>{let writes=0;const existing={async getFileHandle(){writes++;return {name:'JazzDaily.journal.json'};}};await assert.rejects(()=>newJournalFile(existing),/already/);assert.equal(writes,1);let created=false;const blank={async getFileHandle(name,options){if(!options){const e=Error();e.name='NotFoundError';throw e;}created=true;return {name};}};assert.equal((await newJournalFile(blank)).name,'JazzDaily.journal.json');assert.equal(created,true);});
test('folder journal selection excludes backup files and directories',async()=>{const folder={async *values(){yield {kind:'file',name:'b.journal.json'};yield {kind:'directory',name:'dir.json'};yield {kind:'file',name:'a.backup.json'};yield {kind:'file',name:'a.journal.json'};}};assert.deepEqual((await journalFiles(folder)).map(f=>f.name),['a.journal.json','b.journal.json']);});
test('a saved payroll journal round-trips through the same autosave file',async()=>{const db=fixture();db.timecards=[card('c','2026-03-02')];db.payrollRuns=[run(db)];let text='';const h={name:'test.journal.json',async getFile(){return {text:async()=>text};},async createWritable(){let next;return {async write(t){next=t;},async close(){text=next;},async abort(){}};}};const store=new JournalStore(()=>{});assert.equal(await store.saveAs(db,h),true);const loaded=await new JournalStore(()=>{}).open(h);assert.deepEqual(loaded,db);assert.equal(totals(loaded,'2026-03').clear,totals(db,'2026-03').clear);});
